function id = tascar_get_xwindows_id( name )
  [err,res] = system(['LD_LIBRARY_PATH='''' xwininfo -name ''',...
                      name,...
                      ''' | sed -e ''/Window id:/ ! d'' ',...
                      ' -e ''s/.*Window id: \([^[:blank:]]*\).*/\1/''']);
  id = strtrim(res);
end