#!/bin/bash
NUM_CPU=`cat /proc/cpuinfo | grep -e '^processor[^:]*:'|wc -l`
TOOLNAME=cpufreq-set
test -z `which $TOOLNAME` && TOOLNAME=cpufreq-selector
c=0
if test -z "$1"; then
    g="performance"
else
    g="$1"
fi
while test $c -lt $NUM_CPU; do
    $TOOLNAME -c $c -g $g
    let c=$c+1
done
