IF (GLIBMM_FIND_REQUIRED)
    #FIND_PACKAGE(sigc++ REQUIRED)
ELSE (GLIBMM_FIND_REQUIRED)
    FIND_PACKAGE(Glib)
    #FIND_PACKAGE(sigc++)
ENDIF (GLIBMM_FIND_REQUIRED)

IF (GLIB_FOUND)
    #use pkg-config
    FIND_PACKAGE(PkgConfig)
    PKG_CHECK_MODULES(PC_GLIBMM glibmm-2.4)

    FIND_PATH(GLIBMM_INCLUDE_DIR NAMES GLIBMM/main.h HINTS ${PC_GLIBMM_INCLUDEDIR} ${PC_GLIBMM_INCLUDE_DIRS})
    FIND_PATH(GLIBMM_config_INCLUDE_DIR NAMES GLIBMMconfig.h HINTS ${PC_GLIBMM_INCLUDEDIR} ${PC_GLIBMM_INCLUDE_DIRS})
    FIND_LIBRARY(GLIBMM_LIBRARY NAMES GLIBMM GLIBMM-2.4 HINTS ${PC_GLIBMM_LIBDIR} ${PC_GLIBMM_LIBRARY_DIRS})

    SET(GLIBMM_LIBRARIES ${GLIBMM_LIBRARY} ${PC_GLIBMM_PKGCONF_LIBRARIES} ${GLIB_LIBRARIES} ${sigc++_LIBRARIES})
    SET(GLIBMM_INCLUDE_DIRS ${GLIBMM_INCLUDE_DIR} ${GLIBMM_config_INCLUDE_DIR} ${PC_GLIBMM_PKGCONF_INCLUDE_DIRS} ${GLIB_INCLUDE_DIRS} ${SIGC++_INCLUDE_DIRS})

ENDIF (GLIB_FOUND)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Glibmm DEFAULT_MSG GLIBMM_LIBRARIES GLIBMM_INCLUDE_DIRS)

MARK_AS_ADVANCED(GLIBMM_INCLUDE_DIR GLIBMM_config_INCLUDE_DIR GLIBMM_LIBRARY)