if (GLIB_INCLUDE_DIRS AND GLIB_INCLUDE_DIRS)
    set(GLIB_FOUND TRUE)
else ()
    #use pkg-config
    FIND_PACKAGE(PkgConfig)
    PKG_CHECK_MODULES(PC_GLIB glib-2.0)

    FIND_PATH(GLIB_INCLUDE_DIR NAMES glib.h HINTS ${PC_GLIB_INCLUDEDIR} ${PC_GLIB_INCLUDE_DIRS})
    FIND_PATH(GLIB_config_INCLUDE_DIR NAMES glibconfig.h HINTS ${PC_GLIB_INCLUDEDIR} ${PC_GLIB_INCLUDE_DIRS})
    FIND_LIBRARY(GLIB_LIBRARY NAMES glib glib-2.0 HINTS ${PC_GLIB_LIBDIR} ${PC_GLIB_LIBRARY_DIRS})

    SET(GLIB_LIBRARIES ${GLIB_LIBRARY} ${PC_GLIB_PKGCONF_LIBRARIES})
    SET(GLIB_INCLUDE_DIRS ${GLIB_INCLUDE_DIR} ${GLIB_config_INCLUDE_DIR} ${PC_GLIB_PKGCONF_INCLUDE_DIRS})

    INCLUDE(FindPackageHandleStandardArgs)
    FIND_PACKAGE_HANDLE_STANDARD_ARGS(Glib DEFAULT_MSG GLIB_LIBRARY GLIB_INCLUDE_DIR)

    MARK_AS_ADVANCED(GLIB_INCLUDE_DIR GLIB_config_INCLUDE_DIR GLIB_LIBRARY)
endif ()