name: MacOS make

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: fetchall
      run: git fetch --unshallow --tags
    - name: github-cmake workaround
      run: brew uninstall cmake
    - name: dependencies
      run: brew install pkgconfig glibmm jack liblo libsndfile gtkmm3 eigen boost gsl fftw libsamplerate xerces-c libltc gtksourceviewmm3 coreutils adwaita-icon-theme jpeg libmatio cunit labstreaminglayer/tap/lsl
    - name: make
      run: make -j 4
    - name: test
      run: make unit-tests test
